INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('00','Mundial',3),
	 ('1E','Inglaterra',154),
	 ('1I','Irlanda do Norte',0),
	 ('1S','Escócia',0),
	 ('1W','País de Gales',0),
	 ('AD','Andorra',0),
	 ('AE','Emiratos Árabes Unidos',0),
	 ('AF','Afeganistão',356),
	 ('AG','Antigua e Barbuda',0),
	 ('AI','Anguilla',407);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('AL','Albânia',0),
	 ('AM','Arménia',0),
	 ('AN','Antilhas Holandesas',0),
	 ('AO','Angola',160),
	 ('AR','Argentina',7),
	 ('AS','Samoa Americana',381),
	 ('AT','Áustria',148),
	 ('AU','Austrália',161),
	 ('AW','Aruba',0),
	 ('AX','Alândia',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('AZ','Azerbeijão',0),
	 ('BA','Bósnia & Herzegovina',0),
	 ('BB','Barbados',0),
	 ('BD','Bangladesh',0),
	 ('BE','Bélgica',150),
	 ('BF','Burkina Faso',0),
	 ('BG','Bulgária',395),
	 ('BH','Bahrain',0),
	 ('BI','Burundi',0),
	 ('BJ','Benin',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('BM','Bermuda',0),
	 ('BN','Brunei Darussalam',362),
	 ('BO','Bolívia',0),
	 ('BR','Brasil',151),
	 ('BS','Bahamas',0),
	 ('BT','Butão',0),
	 ('BW','Botswana',0),
	 ('BY','Bielorússia',0),
	 ('BZ','Belize',0),
	 ('CA','Canadá',409);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('CD','República Democrática do Congo',0),
	 ('CF','Rep. Centro-Africana',0),
	 ('CG','Congo',0),
	 ('CH','Suíça',294),
	 ('CI','Costa do Marfim',392),
	 ('CK','Ilhas Cook',456),
	 ('CL','Chile',152),
	 ('CM','Camarões',331),
	 ('CN','China',379),
	 ('CO','Colômbia',153);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('CR','Costa Rica',0),
	 ('CU','Cuba',520),
	 ('CV','Cabo Verde',0),
	 ('CY','Chipre',0),
	 ('CZ','República Checa',0),
	 ('DE','Alemanha',149),
	 ('DJ','Djibouti',0),
	 ('DK','Dinamarca',0),
	 ('DM','Dominica',0),
	 ('DO','República Dominicana',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('DZ','Argélia',0),
	 ('EC','Equador',145),
	 ('EE','Estónia',0),
	 ('EG','Egipto',0),
	 ('EN','zw',0),
	 ('ER','Eritreia',0),
	 ('ES','Espanha',139),
	 ('ET','Etiópia',0),
	 ('FI','Finlândia',322),
	 ('FJ','Ilhas Fiji',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('FK','Ilhas Falkland',0),
	 ('FM','Micronésia',0),
	 ('FO','Ilhas Faroé',0),
	 ('FR','França',143),
	 ('GA','Gabão',0),
	 ('GD','Grenada',0),
	 ('GE','Geórgia',0),
	 ('GF','Guiana Francesa',0),
	 ('GG','Guernsey',0),
	 ('GH','Gana',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('GI','Gibraltar',0),
	 ('GL','Groenlândia',0),
	 ('GM','Gâmbia',0),
	 ('GN','Guiné',0),
	 ('GQ','Guiné Equatorial',0),
	 ('GR','Grécia',0),
	 ('GT','Guatemala',0),
	 ('GU','Guam',493),
	 ('GW','Guiné-Bissau',0),
	 ('GY','Guiana',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('HG','Hong-Kong',0),
	 ('HN','Honduras',0),
	 ('HR','Croácia',0),
	 ('HT','Haiti',0),
	 ('HU','Hungria',0),
	 ('ID','Indonésia',0),
	 ('IE','Irlanda',0),
	 ('IL','Israel',0),
	 ('IM','Ilha de Man',0),
	 ('IN','Índia',461);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('IQ','Iraque',0),
	 ('IR','Irão',0),
	 ('IS','Islândia',0),
	 ('IT','Itália',155),
	 ('JE','Jersey',0),
	 ('JM','Jamaica',465),
	 ('JO','Jordânia',0),
	 ('JP','Japão',146),
	 ('KE','Quénia',0),
	 ('KG','Quirgistão',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('KH','Cambodja',0),
	 ('KI','Kiribati',0),
	 ('KM','Comoros',0),
	 ('KN','St Kittis e Nevis',0),
	 ('KP','Coreia do Norte',0),
	 ('KR','Coreia do Sul',0),
	 ('KW','Kuwait',0),
	 ('KY','Ilhas Cayman',0),
	 ('KZ','Cazsaquistão',0),
	 ('LA','Laos',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('LB','Líbano',0),
	 ('LC','Santa Lúcia',0),
	 ('LI','Liechtenstein',0),
	 ('LK','Sri Lanka',0),
	 ('LR','Libéria',0),
	 ('LS','Lesoto',0),
	 ('LT','Lituânia',0),
	 ('LU','Luxemburgo',321),
	 ('LV','Letónia',0),
	 ('LY','Líbia',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('MA','Marrocos',0),
	 ('MC','Mónaco',0),
	 ('MD','Moldávia',0),
	 ('MG','Madagáscar',0),
	 ('MH','Ilhas Marshall',0),
	 ('MK','Macedónia',0),
	 ('ML','Mali',0),
	 ('MM','Mianmar',0),
	 ('MN','Mongólia',0),
	 ('MO','Macau',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('MQ','Martinica',0),
	 ('MR','Mauritânia',0),
	 ('MS','Montserrat',0),
	 ('MT','Malta',0),
	 ('MU','Maurítius',0),
	 ('MV','Maldivas',0),
	 ('MW','Malawi',0),
	 ('MX','México',156),
	 ('MY','Malásia',426),
	 ('MZ','Moçambique',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('NA','Namíbia',0),
	 ('NC','Nova Caledónia',0),
	 ('NE','Níger',0),
	 ('NF','Ilha Norflok',0),
	 ('NG','Nigéria',0),
	 ('NI','Nicarágua',0),
	 ('NL','Holanda',144),
	 ('NO','Noruega',142),
	 ('NP','Nepal',0),
	 ('NR','Nauru',302);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('NZ','Nova Zelândia',0),
	 ('OM','Oman',0),
	 ('PA','Panamá',0),
	 ('PE','Perú',168),
	 ('PF','Polinésia Francesa',463),
	 ('PG','Papua & Nova Guiné',0),
	 ('PH','Filipinas',0),
	 ('PK','Paquistão',0),
	 ('PL','Polónia',0),
	 ('PN','Ilha Pitcairn',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('PR','Porto Rico',0),
	 ('PS','Palestina',0),
	 ('PT','Portugal',4),
	 ('PW','Palau',0),
	 ('PY','Paraguai',157),
	 ('QA','Qatar',0),
	 ('RE','Reunião',0),
	 ('RO','Roménia',304),
	 ('RS','Sérvia e Montenegro',320),
	 ('RU','Rússia',158);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('RW','Ruanda',382),
	 ('SA','Arábia Saudita',0),
	 ('SB','Ilhas Solomão',0),
	 ('SC','Seycheles',0),
	 ('SD','Sudão',0),
	 ('SE','Suécia',0),
	 ('SG','Singapura',0),
	 ('SH','Santa Helena',0),
	 ('SI','Eslovénia',0),
	 ('SK','Eslováquia',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('SL','Serra Leoa',0),
	 ('SM','São Marino',328),
	 ('SN','Senegal',0),
	 ('SO','Somália',513),
	 ('SR','Suriname',0),
	 ('ST','São Tomé & Príncipe',0),
	 ('SV','El Salvador',0),
	 ('SY','Síria',0),
	 ('SZ','Suazilândia',0),
	 ('TC','Ilhas Turcas e Caicos',374);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('TD','Chade',0),
	 ('TG','Togo',462),
	 ('TH','Tailândia',0),
	 ('TJ','Tadiquistão',0),
	 ('TK','Tokelau',0),
	 ('TM','Turkmenistão',0),
	 ('TN','Tunísia',0),
	 ('TO','Tonga',0),
	 ('TP','Timor Leste',0),
	 ('TR','Turquia',358);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('TT','Trinidad e Tobago',0),
	 ('TV','Tuvalu',0),
	 ('TW','Taiwan',0),
	 ('TZ','Tanzânia',0),
	 ('UA','Ucrânia',0),
	 ('UG','Uganda',0),
	 ('UK','Reino Unido',0),
	 ('US','Estados Unidos da América',277),
	 ('UY','Uruguai',159),
	 ('UZ','Uzbequistão',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('VA','Vaticano',0),
	 ('VC','S. Vicente e Grinalda',0),
	 ('VE','Venezuela',430),
	 ('VG','Ilhas Virgens (UK)',0),
	 ('VI','Ilhas Virgens (USA)',0),
	 ('VN','Vietname',0),
	 ('VU','Vanuatu',0),
	 ('WF','Wallis e ilhas Futunas',0),
	 ('WS','Samoa Ocidental',0),
	 ('YE','Iémen',0);
INSERT INTO rh_dev.tcountry (country,countryDesc,groupId) VALUES
	 ('ZA','África do Sul',162),
	 ('ZM','Zâmbia',0),
	 ('ZR','Zaire',377),
	 ('ZW','Zimbabwe',312);
