INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','00','Mundial'),
	 ('BR','1E','Inglaterra'),
	 ('BR','1I','Irlanda do Norte'),
	 ('BR','1S','Escócia'),
	 ('BR','1W','País de Gales'),
	 ('BR','AD','Andorra'),
	 ('BR','AE','Emiratos Árabes Unidos'),
	 ('BR','AF','Afeganistão'),
	 ('BR','AG','Antigua e Barbuda'),
	 ('BR','AI','Anguilla');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','AL','Albânia'),
	 ('BR','AM','Armênia'),
	 ('BR','AN','Antilhas Holandesas'),
	 ('BR','AO','Angola'),
	 ('BR','AR','Argentina'),
	 ('BR','AS','Samoa Americana'),
	 ('BR','AT','Áustria'),
	 ('BR','AU','Austrália'),
	 ('BR','AW','Aruba'),
	 ('BR','AX','Alândia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','AZ','Azerbeijan'),
	 ('BR','BA','Bôsnia & Herzegovina'),
	 ('BR','BB','Barbados'),
	 ('BR','BD','Bangladesh'),
	 ('BR','BE','Bêlgica'),
	 ('BR','BF','Burkina Faso'),
	 ('BR','BG','Bulgária'),
	 ('BR','BH','Bahrain'),
	 ('BR','BI','Burundi'),
	 ('BR','BJ','Benin');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','BM','Bermuda'),
	 ('BR','BN','Brunei Darussalam'),
	 ('BR','BO','Bolívia'),
	 ('BR','BR','Brasil'),
	 ('BR','BS','Bahamas'),
	 ('BR','BT','Butão'),
	 ('BR','BW','Botswana'),
	 ('BR','BY','Bielorússia'),
	 ('BR','BZ','Belize'),
	 ('BR','CA','Canadá');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','CD','República Democrática do Congo'),
	 ('BR','CF','Rep. Centro-Africana'),
	 ('BR','CG','Congo'),
	 ('BR','CH','Suíça'),
	 ('BR','CI','Costa do Marfim'),
	 ('BR','CK','Ilhas Cook'),
	 ('BR','CL','Chile'),
	 ('BR','CM','Camarões'),
	 ('BR','CN','China'),
	 ('BR','CO','Colômbia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','CR','Costa Rica'),
	 ('BR','CU','Cuba'),
	 ('BR','CV','Cabo Verde'),
	 ('BR','CY','Chipre'),
	 ('BR','CZ','República Checa'),
	 ('BR','DE','Alemanha'),
	 ('BR','DJ','Djibouti'),
	 ('BR','DK','Dinamarca'),
	 ('BR','DM','Dominica'),
	 ('BR','DO','República Dominicana');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','DZ','Argêlia'),
	 ('BR','EC','Equador'),
	 ('BR','EE','Estônia'),
	 ('BR','EG','Egipto'),
	 ('BR','ER','Eritreia'),
	 ('BR','ES','Espanha'),
	 ('BR','ET','Etiópia'),
	 ('BR','FI','Finlândia'),
	 ('BR','FJ','Ilhas Fiji'),
	 ('BR','FK','Ilhas Falkland');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','FM','Micronêsia'),
	 ('BR','FO','Ilhas Faroé'),
	 ('BR','FR','França'),
	 ('BR','GA','Gabão'),
	 ('BR','GD','Grenada'),
	 ('BR','GE','Geórgia'),
	 ('BR','GF','Guiana Francesa'),
	 ('BR','GG','Guernsey'),
	 ('BR','GH','Gana'),
	 ('BR','GI','Gibraltar');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','GL','Groenlândia'),
	 ('BR','GM','Gâmbia'),
	 ('BR','GN','Guiné'),
	 ('BR','GQ','Guiné Equatorial'),
	 ('BR','GR','Grécia'),
	 ('BR','GT','Guatemala'),
	 ('BR','GU','Guam'),
	 ('BR','GW','Guiné-Bissau'),
	 ('BR','GY','Guiana'),
	 ('BR','HG','Hong-Kong');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','HN','Honduras'),
	 ('BR','HR','Croácia'),
	 ('BR','HT','Haiti'),
	 ('BR','HU','Hungria'),
	 ('BR','ID','Indonésia'),
	 ('BR','IE','Irlanda'),
	 ('BR','IL','Israel'),
	 ('BR','IM','Ilha de Man'),
	 ('BR','IN','Índia'),
	 ('BR','IQ','Iraque');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','IR','Iran'),
	 ('BR','IS','Islândia'),
	 ('BR','IT','Itália'),
	 ('BR','JE','Jersey'),
	 ('BR','JM','Jamaica'),
	 ('BR','JO','Jordânia'),
	 ('BR','JP','Japão'),
	 ('BR','KE','Quênia'),
	 ('BR','KG','Quirgistan'),
	 ('BR','KH','Cambodja');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','KI','Kiribati'),
	 ('BR','KM','Comoros'),
	 ('BR','KN','St Kittis e Nevis'),
	 ('BR','KP','Coreia do Norte'),
	 ('BR','KR','Coreia do Sul'),
	 ('BR','KW','Kuwait'),
	 ('BR','KY','Ilhas Cayman'),
	 ('BR','KZ','Cazaquistan'),
	 ('BR','LA','Laos'),
	 ('BR','LB','Líbano');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','LC','Santa Lúcia'),
	 ('BR','LI','Liechtenstein'),
	 ('BR','LK','Sri Lanka'),
	 ('BR','LR','Libéria'),
	 ('BR','LS','Lesoto'),
	 ('BR','LT','Lituânia'),
	 ('BR','LU','Luxemburgo'),
	 ('BR','LV','Letônia'),
	 ('BR','LY','Líbia'),
	 ('BR','MA','Marrocos');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','MC','Mónaco'),
	 ('BR','MD','Moldávia'),
	 ('BR','MG','Madagáscar'),
	 ('BR','MH','Ilhas Marshall'),
	 ('BR','MK','Macedônia'),
	 ('BR','ML','Mali'),
	 ('BR','MM','Mianmar'),
	 ('BR','MN','Mongôlia'),
	 ('BR','MO','Macau'),
	 ('BR','MQ','Martinica');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','MR','Mauritânia'),
	 ('BR','MS','Montserrat'),
	 ('BR','MT','Malta'),
	 ('BR','MU','Maurítius'),
	 ('BR','MV','Maldivas'),
	 ('BR','MW','Malawi'),
	 ('BR','MX','México'),
	 ('BR','MY','Malásia'),
	 ('BR','MZ','Moçambique'),
	 ('BR','NA','Namíbia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','NC','Nova Caledônia'),
	 ('BR','NE','Níger'),
	 ('BR','NF','Ilha Norflok'),
	 ('BR','NG','Nigêria'),
	 ('BR','NI','Nicarágua'),
	 ('BR','NL','Holanda'),
	 ('BR','NO','Noruega'),
	 ('BR','NP','Nepal'),
	 ('BR','NR','Nauru'),
	 ('BR','NZ','Nova Zelândia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','OM','Oman'),
	 ('BR','PA','Panamá'),
	 ('BR','PE','Perú'),
	 ('BR','PF','Polinêsia Francesa'),
	 ('BR','PG','Papua & Nova Guiné'),
	 ('BR','PH','Filipinas'),
	 ('BR','PK','Paquistan'),
	 ('BR','PL','Polônia'),
	 ('BR','PN','Ilha Pitcairn'),
	 ('BR','PR','Porto Rico');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','PS','Palestina'),
	 ('BR','PT','Portugal'),
	 ('BR','PW','Palau'),
	 ('BR','PY','Paraguai'),
	 ('BR','QA','Qatar'),
	 ('BR','RE','Reunião'),
	 ('BR','RO','Romênia'),
	 ('BR','RS','Sérvia'),
	 ('BR','RU','Rússia'),
	 ('BR','RW','Ruanda');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','SA','Arábia Saudita'),
	 ('BR','SB','Ilhas Solomão'),
	 ('BR','SC','Seycheles'),
	 ('BR','SD','Sudão'),
	 ('BR','SE','Suécia'),
	 ('BR','SG','Singapura'),
	 ('BR','SH','Santa Helena'),
	 ('BR','SI','Eslovênia'),
	 ('BR','SK','Eslováquia'),
	 ('BR','SL','Serra Leoa');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','SM','São Marino'),
	 ('BR','SN','Senegal'),
	 ('BR','SO','Somália'),
	 ('BR','SR','Suriname'),
	 ('BR','ST','São Tomé & Príncipe'),
	 ('BR','SV','El Salvador'),
	 ('BR','SY','Síria'),
	 ('BR','SZ','Suazilândia'),
	 ('BR','TC','Ilhas Turcas e Caicos'),
	 ('BR','TD','Chade');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','TG','Togo'),
	 ('BR','TH','Tailândia'),
	 ('BR','TJ','Tadiquistan'),
	 ('BR','TK','Tokelau'),
	 ('BR','TM','Turkmenistan'),
	 ('BR','TN','Tunísia'),
	 ('BR','TO','Tonga'),
	 ('BR','TP','Timor Leste'),
	 ('BR','TR','Turquia'),
	 ('BR','TT','Trinidad e Tobago');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','TV','Tuvalu'),
	 ('BR','TW','Taiwan'),
	 ('BR','TZ','Tanzânia'),
	 ('BR','UA','Ucrânia'),
	 ('BR','UG','Uganda'),
	 ('BR','UK','Reino Unido'),
	 ('BR','US','Estados Unidos da América'),
	 ('BR','UY','Uruguai'),
	 ('BR','UZ','Uzbequistan'),
	 ('BR','VA','Vaticano');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','VC','S. Vicente e Grinalda'),
	 ('BR','VE','Venezuela'),
	 ('BR','VG','Ilhas Virgens (UK)'),
	 ('BR','VI','Ilhas Virgens (USA)'),
	 ('BR','VN','Vietname'),
	 ('BR','VU','Vanuatu'),
	 ('BR','WF','Wallis e ilhas Futunas'),
	 ('BR','WS','Samoa Ocidental'),
	 ('BR','YE','Iémen'),
	 ('BR','ZA','África do Sul');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('BR','ZM','Zâmbia'),
	 ('BR','ZR','Zaire'),
	 ('BR','ZW','Zimbabwe'),
	 ('EN','00','World'),
	 ('EN','1E','England'),
	 ('EN','1I','Northern Ireland'),
	 ('EN','1S','Scotland'),
	 ('EN','1W','Wales'),
	 ('EN','AD','Andorra'),
	 ('EN','AE','United Arab Emirates');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','AF','Afghanistan'),
	 ('EN','AG','Antigua and Barbuda'),
	 ('EN','AI','Anguilla'),
	 ('EN','AL','Albania'),
	 ('EN','AM','Armenia'),
	 ('EN','AN','Netherlands Antilles'),
	 ('EN','AO','Angola'),
	 ('EN','AR','Argentina'),
	 ('EN','AS','American Samoa'),
	 ('EN','AT','Austria');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','AU','Australia'),
	 ('EN','AW','Aruba'),
	 ('EN','AX','Aland'),
	 ('EN','AZ','Azerbaijan'),
	 ('EN','BA','Bosnia and Herzegovina'),
	 ('EN','BB','Barbados'),
	 ('EN','BD','Bangladesh'),
	 ('EN','BE','Belgium'),
	 ('EN','BF','Burkina Faso'),
	 ('EN','BG','Bulgaria');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','BH','Bahrain'),
	 ('EN','BI','Burundi'),
	 ('EN','BJ','Benin'),
	 ('EN','BM','Bermuda'),
	 ('EN','BN','Brunei Darussalam'),
	 ('EN','BO','Bolivia'),
	 ('EN','BR','Brazil'),
	 ('EN','BS','Bahamas'),
	 ('EN','BT','Bhutan'),
	 ('EN','BW','Botswana');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','BY','Belarus'),
	 ('EN','BZ','Belize'),
	 ('EN','CA','Canada'),
	 ('EN','CD','Congo DR'),
	 ('EN','CF','Central African Republic'),
	 ('EN','CG','Congo'),
	 ('EN','CH','Switzerland'),
	 ('EN','CI','Côte Divoire'),
	 ('EN','CK','Cook Islands'),
	 ('EN','CL','Chile');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','CM','Cameroon'),
	 ('EN','CN','China'),
	 ('EN','CO','Colombia'),
	 ('EN','CR','Costa Rica'),
	 ('EN','CU','Cuba'),
	 ('EN','CV','Cape Verde'),
	 ('EN','CY','Cyprus'),
	 ('EN','CZ','Czech Republic'),
	 ('EN','DE','Germany'),
	 ('EN','DJ','Djibouti');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','DK','Denmark'),
	 ('EN','DM','Dominica'),
	 ('EN','DO','Dominican Republic'),
	 ('EN','DZ','Algeria'),
	 ('EN','EC','Ecuador'),
	 ('EN','EE','Estonia'),
	 ('EN','EG','Egypt'),
	 ('EN','ER','Eritrea'),
	 ('EN','ES','Spain'),
	 ('EN','ET','Ethiopia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','FI','Finland'),
	 ('EN','FJ','Fiji islands'),
	 ('EN','FK','Falkland Islands'),
	 ('EN','FM','Micronesia'),
	 ('EN','FO','Faeroe Islands'),
	 ('EN','FR','France'),
	 ('EN','GA','Gabon'),
	 ('EN','GD','Grenada'),
	 ('EN','GE','Georgia'),
	 ('EN','GF','French Guiana');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','GG','Guernsey'),
	 ('EN','GH','Ghana'),
	 ('EN','GI','Gibraltar'),
	 ('EN','GL','Greenland'),
	 ('EN','GM','Gambia'),
	 ('EN','GN','Guinea'),
	 ('EN','GQ','Equatorial Guinea'),
	 ('EN','GR','Greece'),
	 ('EN','GT','Guatemala'),
	 ('EN','GU','Guam');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','GW','Guinea-Bissau'),
	 ('EN','GY','Guyana'),
	 ('EN','HG','Hong-Kong'),
	 ('EN','HN','Honduras'),
	 ('EN','HR','Croatia'),
	 ('EN','HT','Haiti'),
	 ('EN','HU','Hungary'),
	 ('EN','ID','Indonesia'),
	 ('EN','IE','Ireland'),
	 ('EN','IL','Israel');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','IM','Isle of Man'),
	 ('EN','IN','India'),
	 ('EN','IQ','Iraq'),
	 ('EN','IR','Iran'),
	 ('EN','IS','Iceland'),
	 ('EN','IT','Italy'),
	 ('EN','JE','Jersey'),
	 ('EN','JM','Jamaica'),
	 ('EN','JO','Jordan'),
	 ('EN','JP','Japan');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','KE','Kenya'),
	 ('EN','KG','Kyrgyzstan'),
	 ('EN','KH','Cambodia'),
	 ('EN','KI','Kiribati'),
	 ('EN','KM','Comoros'),
	 ('EN','KN','St Christopher & Nevis'),
	 ('EN','KP','North Korea'),
	 ('EN','KR','South Korea'),
	 ('EN','KW','Kuwait'),
	 ('EN','KY','Cayman Islands');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','KZ','Kazakhstan'),
	 ('EN','LA','Laos'),
	 ('EN','LB','Lebanon'),
	 ('EN','LC','Saint Lucia'),
	 ('EN','LI','Liechtenstein'),
	 ('EN','LK','Sri Lanka'),
	 ('EN','LR','Liberia'),
	 ('EN','LS','Lesotho'),
	 ('EN','LT','Lithuania'),
	 ('EN','LU','Luxembourg');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','LV','Latvia'),
	 ('EN','LY','Libya'),
	 ('EN','MA','Morocco'),
	 ('EN','MC','Monaco'),
	 ('EN','MD','Moldova'),
	 ('EN','MG','Madagascar'),
	 ('EN','MH','Marshall Islands'),
	 ('EN','MK','Macedonia'),
	 ('EN','ML','Mali'),
	 ('EN','MM','Myanmar');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','MN','Mongolia'),
	 ('EN','MO','Macau'),
	 ('EN','MQ','Martinique'),
	 ('EN','MR','Mauritania'),
	 ('EN','MS','Montserrat'),
	 ('EN','MT','Malta'),
	 ('EN','MU','Mauritius'),
	 ('EN','MV','Maldives'),
	 ('EN','MW','Malawi'),
	 ('EN','MX','Mexico');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','MY','Malaysia'),
	 ('EN','MZ','Mozambique'),
	 ('EN','NA','Namibia'),
	 ('EN','NC','New Caledonia'),
	 ('EN','NE','Niger'),
	 ('EN','NF','Norflok Island'),
	 ('EN','NG','Nigeria'),
	 ('EN','NI','Nicaragua'),
	 ('EN','NL','Netherlands'),
	 ('EN','NO','Norway');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','NP','Nepal'),
	 ('EN','NR','Nauru'),
	 ('EN','NZ','New Zealand'),
	 ('EN','OM','Oman'),
	 ('EN','PA','Panama'),
	 ('EN','PE','Peru'),
	 ('EN','PF','French Polynesia'),
	 ('EN','PG','Papua New Guinea'),
	 ('EN','PH','Philippines'),
	 ('EN','PK','Pakistan');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','PL','Poland'),
	 ('EN','PN','Pitcairn Island'),
	 ('EN','PR','Puerto Rico'),
	 ('EN','PS','Palestina'),
	 ('EN','PT','Portugal'),
	 ('EN','PW','Palau'),
	 ('EN','PY','Paraguay'),
	 ('EN','QA','Qatar'),
	 ('EN','RE','Réunion'),
	 ('EN','RO','Romania');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','RS','Serbia'),
	 ('EN','RU','Russia'),
	 ('EN','RW','Rwanda'),
	 ('EN','SA','Saudi Arabia'),
	 ('EN','SB','Solomon Islands'),
	 ('EN','SC','Seychelles'),
	 ('EN','SD','Sudan'),
	 ('EN','SE','Sweden'),
	 ('EN','SG','Singapore'),
	 ('EN','SH','St. Helena');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','SI','Slovenia'),
	 ('EN','SK','Slovakia'),
	 ('EN','SL','Sierra Leone'),
	 ('EN','SM','San Marino'),
	 ('EN','SN','Senegal'),
	 ('EN','SO','Somalia'),
	 ('EN','SR','Suriname'),
	 ('EN','ST','São Tomé and Príncipe'),
	 ('EN','SV','El Salvador'),
	 ('EN','SY','Syria');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','SZ','Swaziland'),
	 ('EN','TC','Turks & Caicos Islands'),
	 ('EN','TD','Chad'),
	 ('EN','TG','Togo'),
	 ('EN','TH','Thailand'),
	 ('EN','TJ','Tajikistan'),
	 ('EN','TK','Tokelau'),
	 ('EN','TM','Turkmenistan'),
	 ('EN','TN','Tunisia'),
	 ('EN','TO','Tonga');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','TP','East Timor'),
	 ('EN','TR','Turkey'),
	 ('EN','TT','Trinidad and Tobago'),
	 ('EN','TV','Tuvalu'),
	 ('EN','TW','Taiwan'),
	 ('EN','TZ','Tanzania'),
	 ('EN','UA','Ukraine'),
	 ('EN','UG','Uganda'),
	 ('EN','UK','United Kingdom'),
	 ('EN','US','United States');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','UY','Uruguay'),
	 ('EN','UZ','Uzbekistan'),
	 ('EN','VA','Vatican City'),
	 ('EN','VC','St. Vicent and the Grenadines'),
	 ('EN','VE','Venezuela'),
	 ('EN','VG','Virgin Islands (UK)'),
	 ('EN','VI','Virgin Islands (USA)'),
	 ('EN','VN','Vietnam'),
	 ('EN','VU','Vanuatu'),
	 ('EN','WF','Wallis and Futuna Islands');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('EN','WS','Western Samoa'),
	 ('EN','YE','Yemen'),
	 ('EN','ZA','South Africa'),
	 ('EN','ZM','Zambia'),
	 ('EN','ZR','Zaire'),
	 ('EN','ZW','Zimbabwe'),
	 ('PT','00','Mundial'),
	 ('PT','1E','Inglaterra'),
	 ('PT','1I','Irlanda do Norte'),
	 ('PT','1S','Escócia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','1W','País de Gales'),
	 ('PT','AD','Andorra'),
	 ('PT','AE','Emiratos Árabes Unidos'),
	 ('PT','AF','Afeganistão'),
	 ('PT','AG','Antigua e Barbuda'),
	 ('PT','AI','Anguilla'),
	 ('PT','AL','Albânia'),
	 ('PT','AM','Arménia'),
	 ('PT','AN','Antilhas Holandesas'),
	 ('PT','AO','Angola');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','AR','Argentina'),
	 ('PT','AS','Samoa Americana'),
	 ('PT','AT','Áustria'),
	 ('PT','AU','Austrália'),
	 ('PT','AW','Aruba'),
	 ('PT','AX','Alândia'),
	 ('PT','AZ','Azerbeijão'),
	 ('PT','BA','Bósnia & Herzegovina'),
	 ('PT','BB','Barbados'),
	 ('PT','BD','Bangladesh');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','BE','Bélgica'),
	 ('PT','BF','Burkina Faso'),
	 ('PT','BG','Bulgária'),
	 ('PT','BH','Bahrain'),
	 ('PT','BI','Burundi'),
	 ('PT','BJ','Benin'),
	 ('PT','BM','Bermuda'),
	 ('PT','BN','Brunei Darussalam'),
	 ('PT','BO','Bolívia'),
	 ('PT','BR','Brasil');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','BS','Bahamas'),
	 ('PT','BT','Butão'),
	 ('PT','BW','Botswana'),
	 ('PT','BY','Bielorússia'),
	 ('PT','BZ','Belize'),
	 ('PT','CA','Canadá'),
	 ('PT','CD','República Democrática do Congo'),
	 ('PT','CF','Rep. Centro-Africana'),
	 ('PT','CG','Congo'),
	 ('PT','CH','Suíça');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','CI','Costa do Marfim'),
	 ('PT','CK','Ilhas Cook'),
	 ('PT','CL','Chile'),
	 ('PT','CM','Camarões'),
	 ('PT','CN','China'),
	 ('PT','CO','Colômbia'),
	 ('PT','CR','Costa Rica'),
	 ('PT','CU','Cuba'),
	 ('PT','CV','Cabo Verde'),
	 ('PT','CY','Chipre');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','CZ','República Checa'),
	 ('PT','DE','Alemanha'),
	 ('PT','DJ','Djibouti'),
	 ('PT','DK','Dinamarca'),
	 ('PT','DM','Dominica'),
	 ('PT','DO','República Dominicana'),
	 ('PT','DZ','Argélia'),
	 ('PT','EC','Equador'),
	 ('PT','EE','Estónia'),
	 ('PT','EG','Egipto');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','ER','Eritreia'),
	 ('PT','ES','Espanha'),
	 ('PT','ET','Etiópia'),
	 ('PT','FI','Finlândia'),
	 ('PT','FJ','Ilhas Fiji'),
	 ('PT','FK','Ilhas Falkland'),
	 ('PT','FM','Micronésia'),
	 ('PT','FO','Ilhas Faroé'),
	 ('PT','FR','França'),
	 ('PT','GA','Gabão');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','GD','Grenada'),
	 ('PT','GE','Geórgia'),
	 ('PT','GF','Guiana Francesa'),
	 ('PT','GG','Guernsey'),
	 ('PT','GH','Gana'),
	 ('PT','GI','Gibraltar'),
	 ('PT','GL','Groenlândia'),
	 ('PT','GM','Gâmbia'),
	 ('PT','GN','Guiné'),
	 ('PT','GQ','Guiné Equatorial');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','GR','Grécia'),
	 ('PT','GT','Guatemala'),
	 ('PT','GU','Guam'),
	 ('PT','GW','Guiné-Bissau'),
	 ('PT','GY','Guiana'),
	 ('PT','HG','Hong-Kong'),
	 ('PT','HN','Honduras'),
	 ('PT','HR','Croácia'),
	 ('PT','HT','Haiti'),
	 ('PT','HU','Hungria');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','ID','Indonésia'),
	 ('PT','IE','Irlanda'),
	 ('PT','IL','Israel'),
	 ('PT','IM','Ilha de Man'),
	 ('PT','IN','Índia'),
	 ('PT','IQ','Iraque'),
	 ('PT','IR','Irão'),
	 ('PT','IS','Islândia'),
	 ('PT','IT','Itália'),
	 ('PT','JE','Jersey');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','JM','Jamaica'),
	 ('PT','JO','Jordânia'),
	 ('PT','JP','Japão'),
	 ('PT','KE','Quénia'),
	 ('PT','KG','Quirgistão'),
	 ('PT','KH','Cambodja'),
	 ('PT','KI','Kiribati'),
	 ('PT','KM','Comoros'),
	 ('PT','KN','St Kittis e Nevis'),
	 ('PT','KP','Coreia do Norte');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','KR','Coreia do Sul'),
	 ('PT','KW','Kuwait'),
	 ('PT','KY','Ilhas Cayman'),
	 ('PT','KZ','Cazsaquistão'),
	 ('PT','LA','Laos'),
	 ('PT','LB','Líbano'),
	 ('PT','LC','Santa Lúcia'),
	 ('PT','LI','Liechtenstein'),
	 ('PT','LK','Sri Lanka'),
	 ('PT','LR','Libéria');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','LS','Lesoto'),
	 ('PT','LT','Lituânia'),
	 ('PT','LU','Luxemburgo'),
	 ('PT','LV','Letónia'),
	 ('PT','LY','Líbia'),
	 ('PT','MA','Marrocos'),
	 ('PT','MC','Mónaco'),
	 ('PT','MD','Moldávia'),
	 ('PT','MG','Madagáscar'),
	 ('PT','MH','Ilhas Marshall');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','MK','Macedónia'),
	 ('PT','ML','Mali'),
	 ('PT','MM','Mianmar'),
	 ('PT','MN','Mongólia'),
	 ('PT','MO','Macau'),
	 ('PT','MQ','Martinica'),
	 ('PT','MR','Mauritânia'),
	 ('PT','MS','Montserrat'),
	 ('PT','MT','Malta'),
	 ('PT','MU','Maurítius');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','MV','Maldivas'),
	 ('PT','MW','Malawi'),
	 ('PT','MX','México'),
	 ('PT','MY','Malásia'),
	 ('PT','MZ','Moçambique'),
	 ('PT','NA','Namíbia'),
	 ('PT','NC','Nova Caledónia'),
	 ('PT','NE','Níger'),
	 ('PT','NF','Ilha Norflok'),
	 ('PT','NG','Nigéria');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','NI','Nicarágua'),
	 ('PT','NL','Holanda'),
	 ('PT','NO','Noruega'),
	 ('PT','NP','Nepal'),
	 ('PT','NR','Nauru'),
	 ('PT','NZ','Nova Zelândia'),
	 ('PT','OM','Oman'),
	 ('PT','PA','Panamá'),
	 ('PT','PE','Perú'),
	 ('PT','PF','Polinésia Francesa');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','PG','Papua & Nova Guiné'),
	 ('PT','PH','Filipinas'),
	 ('PT','PK','Paquistão'),
	 ('PT','PL','Polónia'),
	 ('PT','PN','Ilha Pitcairn'),
	 ('PT','PR','Porto Rico'),
	 ('PT','PS','Palestina'),
	 ('PT','PT','Portugal'),
	 ('PT','PW','Palau'),
	 ('PT','PY','Paraguai');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','QA','Qatar'),
	 ('PT','RE','Reunião'),
	 ('PT','RO','Roménia'),
	 ('PT','RS','Sérvia'),
	 ('PT','RU','Rússia'),
	 ('PT','RW','Ruanda'),
	 ('PT','SA','Arábia Saudita'),
	 ('PT','SB','Ilhas Solomão'),
	 ('PT','SC','Seycheles'),
	 ('PT','SD','Sudão');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','SE','Suécia'),
	 ('PT','SG','Singapura'),
	 ('PT','SH','Santa Helena'),
	 ('PT','SI','Eslovénia'),
	 ('PT','SK','Eslováquia'),
	 ('PT','SL','Serra Leoa'),
	 ('PT','SM','São Marino'),
	 ('PT','SN','Senegal'),
	 ('PT','SO','Somália'),
	 ('PT','SR','Suriname');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','ST','São Tomé & Príncipe'),
	 ('PT','SV','El Salvador'),
	 ('PT','SY','Síria'),
	 ('PT','SZ','Suazilândia'),
	 ('PT','TC','Ilhas Turcas e Caicos'),
	 ('PT','TD','Chade'),
	 ('PT','TG','Togo'),
	 ('PT','TH','Tailândia'),
	 ('PT','TJ','Tadiquistão'),
	 ('PT','TK','Tokelau');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','TM','Turkmenistão'),
	 ('PT','TN','Tunísia'),
	 ('PT','TO','Tonga'),
	 ('PT','TP','Timor Leste'),
	 ('PT','TR','Turquia'),
	 ('PT','TT','Trinidad e Tobago'),
	 ('PT','TV','Tuvalu'),
	 ('PT','TW','Taiwan'),
	 ('PT','TZ','Tanzânia'),
	 ('PT','UA','Ucrânia');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','UG','Uganda'),
	 ('PT','UK','Reino Unido'),
	 ('PT','US','Estados Unidos da América'),
	 ('PT','UY','Uruguai'),
	 ('PT','UZ','Uzbequistão'),
	 ('PT','VA','Vaticano'),
	 ('PT','VC','S. Vicente e Grinalda'),
	 ('PT','VE','Venezuela'),
	 ('PT','VG','Ilhas Virgens (UK)'),
	 ('PT','VI','Ilhas Virgens (USA)');
INSERT INTO rh_dev.tcountrydesc (lang,country,countryDesc) VALUES
	 ('PT','VN','Vietname'),
	 ('PT','VU','Vanuatu'),
	 ('PT','WF','Wallis e ilhas Futunas'),
	 ('PT','WS','Samoa Ocidental'),
	 ('PT','YE','Iémen'),
	 ('PT','ZA','África do Sul'),
	 ('PT','ZM','Zâmbia'),
	 ('PT','ZR','Zaire'),
	 ('PT','ZW','Zimbabwe');
